/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author UserW7
 */
public class MainFrame extends javax.swing.JFrame {
    
    String vrCQL = null;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        // READ TAB
        jtfMatchLimitN.setText("25");
        jtfMatchLimitR.setText("50");
        // CREATE TAB
        jtfNodeProperty1.setText("name");
        jtfNodeProperty2.setText("surname");
        setCreateNodeCBox();
        setCreatePropertyCBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtaTextfield = new javax.swing.JTextArea();
        btnExit = new javax.swing.JButton();
        btnClearTextfield = new javax.swing.JButton();
        jtpTab1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnMatchNodeSel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtfMatchLimitN = new javax.swing.JTextField();
        jcbSelectNode = new javax.swing.JComboBox<>();
        btnMatchNodeText = new javax.swing.JButton();
        jtfMatchNText = new javax.swing.JTextField();
        tnRDReadANode = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btnMatchRelationSel = new javax.swing.JButton();
        btnMatchRelationText = new javax.swing.JButton();
        jtfMatchRText = new javax.swing.JTextField();
        jcbSelectRelation = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jtfMatchLimitR = new javax.swing.JTextField();
        tnRDReadARel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jcbSelCreateNode = new javax.swing.JComboBox<>();
        jtfNodeProperty1 = new javax.swing.JTextField();
        btnCreateNode = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtfNodeProperty2 = new javax.swing.JTextField();
        jtfNodePropertyValue1 = new javax.swing.JTextField();
        jtfNodePropertyValue2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        btnCreateRelation = new javax.swing.JButton();
        jtfRelProperty1 = new javax.swing.JTextField();
        jcbSelCreateRelation = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtfRelPropertyValue1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jcbSelFromNode = new javax.swing.JComboBox<>();
        jcbSelToNode = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jtfFromNodeProperty1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jtfFromNodePropertyValue1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jtfToNodeProperty1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jtfToNodePropertyValue1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        btnDeleteNodeByID = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtfMatchNodeID = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        btnDeleteRelationByID = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jtfMatchRelationID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtaTextfield.setColumns(20);
        jtaTextfield.setRows(5);
        jScrollPane1.setViewportView(jtaTextfield);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnClearTextfield.setText("Clear Textfield");
        btnClearTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearTextfieldActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Match by Nodes"));

        btnMatchNodeSel.setText("Match Selection");
        btnMatchNodeSel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatchNodeSelActionPerformed(evt);
            }
        });

        jLabel2.setText("Limit to:");

        jtfMatchLimitN.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfMatchLimitN.setText("25");

        jcbSelectNode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clients", "Developers", "Projects", "Stacks" }));

        btnMatchNodeText.setText("Match Text");
        btnMatchNodeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatchNodeTextActionPerformed(evt);
            }
        });

        jtfMatchNText.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        tnRDReadANode.setText("Match all Nodes");
        tnRDReadANode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnRDReadANodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMatchNodeText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tnRDReadANode, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(btnMatchNodeSel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfMatchLimitN))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbSelectNode, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfMatchNText, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMatchNodeSel)
                    .addComponent(jcbSelectNode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMatchNodeText)
                    .addComponent(jtfMatchNText))
                .addGap(13, 13, 13)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfMatchLimitN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tnRDReadANode))
                .addGap(6, 6, 6))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Match by Relationship"));

        btnMatchRelationSel.setText("Match Selection");
        btnMatchRelationSel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatchRelationSelActionPerformed(evt);
            }
        });

        btnMatchRelationText.setText("Match Text");
        btnMatchRelationText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatchRelationTextActionPerformed(evt);
            }
        });

        jtfMatchRText.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jcbSelectRelation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ENGAGED_IN", "ORDERS_FOR", "STACKED_ON" }));

        jLabel3.setText("Limit to:");

        jtfMatchLimitR.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfMatchLimitR.setText("25");

        tnRDReadARel.setText("Match all Relations");
        tnRDReadARel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnRDReadARelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tnRDReadARel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMatchRelationText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMatchRelationSel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jtfMatchLimitR, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfMatchRText, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcbSelectRelation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMatchRelationSel)
                    .addComponent(jcbSelectRelation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMatchRelationText)
                    .addComponent(jtfMatchRText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tnRDReadARel)
                    .addComponent(jLabel3)
                    .addComponent(jtfMatchLimitR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtpTab1.addTab("READ", jPanel1);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Create a new Node"));

        jcbSelCreateNode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clients", "Developers", "Projects", "Stacks" }));
        jcbSelCreateNode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbSelCreateNodeItemStateChanged(evt);
            }
        });

        jtfNodeProperty1.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        btnCreateNode.setText("Create New Node");
        btnCreateNode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNodeActionPerformed(evt);
            }
        });

        jLabel1.setText("Select the new node:");

        jtfNodeProperty2.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jtfNodePropertyValue1.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jtfNodePropertyValue2.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel4.setText("Property 1:");

        jLabel5.setText("Property 2:");

        jLabel6.setText("Value 1:");

        jLabel7.setText("Value 2:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtfNodeProperty2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                    .addComponent(jtfNodeProperty1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfNodePropertyValue1)
                                    .addComponent(jtfNodePropertyValue2)))
                            .addComponent(jcbSelCreateNode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnCreateNode, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbSelCreateNode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNodeProperty1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNodePropertyValue1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNodeProperty2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNodePropertyValue2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateNode)
                .addGap(5, 5, 5))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Create a new Relationship"));

        btnCreateRelation.setText("Create New Relation");
        btnCreateRelation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateRelationActionPerformed(evt);
            }
        });

        jtfRelProperty1.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jcbSelCreateRelation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ENGAGED_IN", "ORDERS_FOR", "STACKED_ON" }));
        jcbSelCreateRelation.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbSelCreateRelationItemStateChanged(evt);
            }
        });

        jLabel10.setText("Property 1:");

        jLabel11.setText("Value 1:");

        jtfRelPropertyValue1.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel12.setText("Select the new relation:");

        jLabel13.setText("From Node:");

        jcbSelFromNode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clients", "Developers", "Projects", "Stacks" }));
        jcbSelFromNode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbSelFromNodeItemStateChanged(evt);
            }
        });

        jcbSelToNode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clients", "Developers", "Projects", "Stacks" }));
        jcbSelToNode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbSelToNodeItemStateChanged(evt);
            }
        });

        jLabel14.setText("To Node:");

        jLabel15.setText("Property 1:");

        jtfFromNodeProperty1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtfFromNodeProperty1.setText("name");
        jtfFromNodeProperty1.setToolTipText("");

        jLabel16.setText("Value 1:");

        jtfFromNodePropertyValue1.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel17.setText("Property 1:");

        jtfToNodeProperty1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtfToNodeProperty1.setText("name");
        jtfToNodeProperty1.setToolTipText("");

        jLabel18.setText("Value 1:");

        jtfToNodePropertyValue1.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addComponent(jtfToNodeProperty1)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfToNodePropertyValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jcbSelToNode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jtfFromNodeProperty1)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfFromNodePropertyValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jcbSelFromNode, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnCreateRelation, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(106, 106, 106))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addComponent(jtfRelProperty1)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfRelPropertyValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jcbSelCreateRelation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jcbSelFromNode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfFromNodeProperty1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfFromNodePropertyValue1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(17, 17, 17)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbSelCreateRelation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfRelProperty1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jtfRelPropertyValue1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jcbSelToNode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfToNodeProperty1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfToNodePropertyValue1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addComponent(btnCreateRelation)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        jtpTab1.addTab("CREATE", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );

        jtpTab1.addTab("MODIFY", jPanel3);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Delete Node by ID"));

        btnDeleteNodeByID.setText("Delete Node by ID");
        btnDeleteNodeByID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteNodeByIDActionPerformed(evt);
            }
        });

        jLabel8.setText("Write the Node ID in order to delete:");

        jtfMatchNodeID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDeleteNodeByID, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfMatchNodeID, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteNodeByID)
                    .addComponent(jLabel8)
                    .addComponent(jtfMatchNodeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Delete Relation by ID"));

        btnDeleteRelationByID.setText("Delete Relation by ID");
        btnDeleteRelationByID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRelationByIDActionPerformed(evt);
            }
        });

        jLabel9.setText("Write the Node ID in order to delete:");

        jtfMatchRelationID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDeleteRelationByID, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfMatchRelationID)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteRelationByID)
                    .addComponent(jLabel9)
                    .addComponent(jtfMatchRelationID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(465, Short.MAX_VALUE))
        );

        jtpTab1.addTab("DELETE", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtpTab1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnClearTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                        .addComponent(btnExit))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnClearTextfield)
                            .addComponent(btnExit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addComponent(jtpTab1))
                .addContainerGap())
        );

        jtpTab1.getAccessibleContext().setAccessibleName("Read");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnClearTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearTextfieldActionPerformed
        // TODO add your handling code here:
        jtaTextfield.setText("");    
    }//GEN-LAST:event_btnClearTextfieldActionPerformed

    
    // READ TAB
    // --------
    
    private void tnRDReadANodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnRDReadANodeActionPerformed
        // TODO add your handling code here:
        vrCQL = "MATCH (n) RETURN n LIMIT " + jtfMatchLimitN.getText();
        jtaTextfield.setText(vrCQL + "\n\n");
        try {
            Connection(vrCQL);
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            jtaTextfield.append("Exception catched...\n" + ex.toString());
        }
    }//GEN-LAST:event_tnRDReadANodeActionPerformed

    private void tnRDReadARelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnRDReadARelActionPerformed
        // TODO add your handling code here:
        vrCQL = "MATCH n=()-->() RETURN n LIMIT " + jtfMatchLimitR.getText();
        jtaTextfield.setText(vrCQL + "\n\n");
        try {
            Connection(vrCQL);
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            jtaTextfield.append("Exception catched...\n" + ex.toString());
        }
    }//GEN-LAST:event_tnRDReadARelActionPerformed

    private void btnMatchNodeSelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatchNodeSelActionPerformed
        // TODO add your handling code here:
        vrCQL = "MATCH (n:" + jcbSelectNode.getSelectedItem() + ") RETURN n LIMIT " + jtfMatchLimitN.getText();
        jtaTextfield.setText(vrCQL + "\n\n");
        try {
            Connection(vrCQL);
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            jtaTextfield.append("Exception catched...\n" + ex.toString());
        }
    }//GEN-LAST:event_btnMatchNodeSelActionPerformed

    private void btnMatchNodeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatchNodeTextActionPerformed
        // TODO add your handling code here:
        vrCQL = "MATCH (n:" + jtfMatchNText.getText() + ") RETURN n LIMIT " + jtfMatchLimitN.getText();
        jtaTextfield.setText(vrCQL + "\n\n");
        try {
            Connection(vrCQL);
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            jtaTextfield.append("Exception catched...\n" + ex.toString());
        } 
    }//GEN-LAST:event_btnMatchNodeTextActionPerformed

    private void btnMatchRelationSelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatchRelationSelActionPerformed
        // TODO add your handling code here:
        vrCQL = "MATCH n=()-[r:" + jcbSelectRelation.getSelectedItem() + "]->() RETURN n LIMIT " + jtfMatchLimitR.getText();
        jtaTextfield.setText(vrCQL + "\n\n");
        try {
            Connection(vrCQL);
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            jtaTextfield.append("Exception catched...\n" + ex.toString());
        }
    }//GEN-LAST:event_btnMatchRelationSelActionPerformed

    private void btnMatchRelationTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatchRelationTextActionPerformed
        // TODO add your handling code here: jtfMatchRText
        vrCQL = "MATCH n=()-[r:" + jtfMatchRText.getText() + "]->() RETURN n LIMIT " + jtfMatchLimitR.getText();
        jtaTextfield.setText(vrCQL + "\n\n");
        try {
            Connection(vrCQL);
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            jtaTextfield.append("Exception catched...\n" + ex.toString());
        }
    }//GEN-LAST:event_btnMatchRelationTextActionPerformed

    // CREATE TAB
    // --------
    
    private void btnCreateNodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNodeActionPerformed
        // TODO add your handling code here:
        String vrLabel = jcbSelCreateNode.getSelectedItem().toString();
        String vrProperty1 = jtfNodeProperty1.getText();
        String vrPrtValue1 = jtfNodePropertyValue1.getText();
        String vrProperty2 = jtfNodeProperty2.getText();
        String vrPrtValue2 = jtfNodePropertyValue2.getText();
        if ( jcbSelCreateNode.getSelectedItem().toString() == "Developers" ) {
            vrCQL = "CREATE (n:" + vrLabel + " {" + vrProperty1 +":'" + vrPrtValue1 + "', " + vrProperty2 + ":'" + vrPrtValue2 + "'}) RETURN n";
        } else {
            vrCQL = "CREATE (n:" + vrLabel + " {" + vrProperty1 +":'" + vrPrtValue1 + "'}) RETURN n";
        }
        jtaTextfield.setText(vrCQL + "\n\n");
        try {
            Connection(vrCQL);
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            jtaTextfield.append("Exception catched...\n" + ex.toString());
        }   
    }//GEN-LAST:event_btnCreateNodeActionPerformed
    
    void setCreateNodeCBox() {
        if ( jcbSelCreateNode.getSelectedItem().toString() == "Clients" ) {
            jtfNodeProperty2.setEnabled(false);
            jtfNodePropertyValue2.setEnabled(false);
        }
        if ( jcbSelCreateNode.getSelectedItem().toString() == "Developers" ) {
            jtfNodeProperty2.setEnabled(true);
            jtfNodePropertyValue2.setEnabled(true);
        }
        if ( jcbSelCreateNode.getSelectedItem().toString() == "Projects" ) {
            jtfNodeProperty2.setEnabled(false);
            jtfNodePropertyValue2.setEnabled(false);
        }
        if ( jcbSelCreateNode.getSelectedItem().toString() == "Stacks" ) {
            jtfNodeProperty2.setEnabled(false);
            jtfNodePropertyValue2.setEnabled(false);
        } 
    }
        
    private void btnCreateRelationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateRelationActionPerformed
        // TODO add your handling code here:
        String vrLabel = jcbSelCreateRelation.getSelectedItem().toString();
        String vrProperty1 = jtfRelProperty1.getText();
        String vrPrtValue1 = jtfRelPropertyValue1.getText();
        String vrFromNode = jcbSelFromNode.getSelectedItem().toString();
        String vrFromNodePr1 = jtfFromNodeProperty1.getText();
        String vrFromNodePV1 = jtfFromNodePropertyValue1.getText();
        String vrToNode = jcbSelToNode.getSelectedItem().toString();
        String vrToNodePr1 = jtfToNodeProperty1.getText();
        String vrToNodePV1 = jtfToNodePropertyValue1.getText();
        vrCQL = "MATCH (a:" + vrFromNode + "{" + vrFromNodePr1 + ":'" + vrFromNodePV1 + "'}), "
              + "(b:" + vrToNode +  "{" + vrToNodePr1 + ":'" + vrToNodePV1 + "'}) "
              + "CREATE (a)-[r:" + vrLabel + "{" + vrProperty1 + ":'" + vrPrtValue1 +"'}]->(b) ";
              //+ "RETURN a,b";
        jtaTextfield.setText(vrCQL + "\n\n");
        try {
            Connection(vrCQL);
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            jtaTextfield.append("Exception catched...\n" + ex.toString());
        } 
    }//GEN-LAST:event_btnCreateRelationActionPerformed

    void setCreatePropertyCBox() {
        if ( jcbSelCreateRelation.getSelectedItem().toString() == "ENGAGED_IN" ) {
            jtfRelProperty1.setText("skill");
        }
        if ( jcbSelCreateRelation.getSelectedItem().toString() == "ORDERS_FOR" ) {
            jtfRelProperty1.setText("data");
        }
        if ( jcbSelCreateRelation.getSelectedItem().toString() == "STACKED_ON" ) {
            jtfRelProperty1.setText("usage");
        }
    }
       
    // DELETE TAB
    // --------
    
    private void btnDeleteNodeByIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteNodeByIDActionPerformed
        // TODO add your handling code here:
        vrCQL = "MATCH (n) where id(n) = " + jtfMatchNodeID.getText() + " DETACH DELETE n";
        jtaTextfield.setText(vrCQL + "\n\n");
        try {
            Connection(vrCQL);
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            jtaTextfield.append("Exception catched...\n" + ex.toString());
        }  
    }//GEN-LAST:event_btnDeleteNodeByIDActionPerformed

    private void jcbSelCreateNodeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbSelCreateNodeItemStateChanged
        // TODO add your handling code here:
        setCreateNodeCBox();
    }//GEN-LAST:event_jcbSelCreateNodeItemStateChanged

    private void btnDeleteRelationByIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRelationByIDActionPerformed
        // TODO add your handling code here:
        vrCQL = "Match ()-[r]-() Where ID(r)=" + jtfMatchRelationID.getText() + " Delete r";
        jtaTextfield.setText(vrCQL + "\n\n");
        try {
            Connection(vrCQL);
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            jtaTextfield.append("Exception catched...\n" + ex.toString());
        }  
    }//GEN-LAST:event_btnDeleteRelationByIDActionPerformed

    private void jcbSelFromNodeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbSelFromNodeItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbSelFromNodeItemStateChanged

    private void jcbSelToNodeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbSelToNodeItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbSelToNodeItemStateChanged

    private void jcbSelCreateRelationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbSelCreateRelationItemStateChanged
        // TODO add your handling code here:
        setCreatePropertyCBox();
    }//GEN-LAST:event_jcbSelCreateRelationItemStateChanged

    // Java JDBC caller
    private void Connection(String vrCQL) throws SQLException{
        hourglassCursor();
        Connection con = null;
        Statement stmt = null;
        ResultSet rs = null;
        // Connect
        try {
            con = DriverManager.getConnection("jdbc:neo4j:bolt://localhost", "neo4j", "password");
            stmt = con.createStatement();
            rs = stmt.executeQuery(vrCQL);
            while (rs.next()) {
                jtaTextfield.append(rs.getString("n")+ "\n");
            }
        } catch(SQLException ex) {
            jtaTextfield.append("Exception catched...\n" + ex.toString());
            normalCursor();
        } finally {
            con.close();
            stmt.close();
            rs.close();
        }
        normalCursor();
    }
    
    void hourglassCursor() {
        Cursor hourglassCursor = new Cursor(Cursor.WAIT_CURSOR);
        setCursor(hourglassCursor);
    }

    void normalCursor() {
        Cursor normalCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(normalCursor);
    }
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearTextfield;
    private javax.swing.JButton btnCreateNode;
    private javax.swing.JButton btnCreateRelation;
    private javax.swing.JButton btnDeleteNodeByID;
    private javax.swing.JButton btnDeleteRelationByID;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnMatchNodeSel;
    private javax.swing.JButton btnMatchNodeText;
    private javax.swing.JButton btnMatchRelationSel;
    private javax.swing.JButton btnMatchRelationText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbSelCreateNode;
    private javax.swing.JComboBox<String> jcbSelCreateRelation;
    private javax.swing.JComboBox<String> jcbSelFromNode;
    private javax.swing.JComboBox<String> jcbSelToNode;
    private javax.swing.JComboBox<String> jcbSelectNode;
    private javax.swing.JComboBox<String> jcbSelectRelation;
    private javax.swing.JTextArea jtaTextfield;
    private javax.swing.JTextField jtfFromNodeProperty1;
    private javax.swing.JTextField jtfFromNodePropertyValue1;
    private javax.swing.JTextField jtfMatchLimitN;
    private javax.swing.JTextField jtfMatchLimitR;
    private javax.swing.JTextField jtfMatchNText;
    private javax.swing.JTextField jtfMatchNodeID;
    private javax.swing.JTextField jtfMatchRText;
    private javax.swing.JTextField jtfMatchRelationID;
    private javax.swing.JTextField jtfNodeProperty1;
    private javax.swing.JTextField jtfNodeProperty2;
    private javax.swing.JTextField jtfNodePropertyValue1;
    private javax.swing.JTextField jtfNodePropertyValue2;
    private javax.swing.JTextField jtfRelProperty1;
    private javax.swing.JTextField jtfRelPropertyValue1;
    private javax.swing.JTextField jtfToNodeProperty1;
    private javax.swing.JTextField jtfToNodePropertyValue1;
    private javax.swing.JTabbedPane jtpTab1;
    private javax.swing.JButton tnRDReadANode;
    private javax.swing.JButton tnRDReadARel;
    // End of variables declaration//GEN-END:variables
}
